language: ruby
rvm:
  - 2.4
sudo: required
dist: trusty
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable fluxbox
    - google-chrome-beta
before_install:
  - nvm install node
  - npm install -g @angular/cli
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - cd ng2rhmusic && npm install
  - cd ..
script:
  - bundle exec rspec
  - cd ng2rhmusic && ng test --single-run
